### ISSUE TITLE
Missing folders in warmup lambda once deployed on newer serverless versions

### ISSUE THREAD

**Issue by haywiremk** [juanjoDiaz/serverless-plugin-warmup#344] opened 2023-10-06 18:59 UTC
I am now seeing the following error using the warmup plugin
{
message:"Error: Cannot find module './serverless_sdk/index.js'
Require stack:
- /var/task/s_warmUpPluginDefault.js
- /opt/sls-sdk-node/wrapper.js
- /var/runtime/index.mjs"
name:"Runtime.ImportModuleError"
type:"ERROR_TYPE_UNCAUGHT"
}

When I look at the warmup-plugin-default lambda I do not see the ./serverless_sdk or ./.warmup folders.  I think something may have changed in the newer serverless frameworks.  I now only see the s_warmUpPluginDefault.js being deployed to the lambda.  Not sure how to resolve this other than disable the plugin.

Framework Core: 3.35.2 (local) 3.35.2 (global)
Plugin: 7.0.5
SDK: 4.4.0

**Comment by juanjoDiaz** [comment] 2023-10-12 17:42
Hi @haywiremk ,

What did you change to start seeing this?
The Framework version? The SDK version?

This kind of issue are almost always caused by different plugins not playing along nicely due to unclarity on which lifecycle events plugins should use (I've complain to the serverless maintainers about this for years...).

When talking about SDK, are you talking about the Dashboard SDK?
Sometime ago we had #310 which might be related.

**Comment by MrPeker** [comment] 2023-10-15 02:54
Hi,

I encountered the same problem you described, which seems to stem from the Serverless Dashboard SDK. Specifically, the SDK's wrapper function attempts to access a file in the `serverless_sdk` folder. Because this folder isn't included in the deployed package, it triggers an error.

As a temporary solution, I changed the packaging configuration to include all files, using the following settings:
```
package: { individually: false, patterns: ['**'] }
```

**Comment by juanjoDiaz** [comment] 2023-12-12 07:45
Glad to found a work around.

Please keep in mind that `'**'` is adding the entire folder to the package.
If you do that, you probably don't want to package individually.
If you package individually you probably want more specific selectors. From the linked issue:
```yaml
      patterns:
          - "!../**"
          - "!../../**"
          - ./serverless_sdk/*
          - ./s_warmUpPluginDefault.js
```

Closing this for now as there is much more that I can do here.

**Closed by juanjoDiaz** 2023-12-12 07:45 UTC
