### ISSUE TITLE
Datadog plugin integration errors

### ISSUE THREAD

**Issue by judehunter** [juanjoDiaz/serverless-plugin-warmup#231] opened 2020-12-03 21:47 UTC
I tried using this plugin with the `serverless-datadog-plugin`, but I get errors when EventBridge tries to invoke the function.
Presumably because of the fact that the datadog plugin installs and attaches a Lambda Layer to the function, which the warmup function has troubles with? Not sure though.
The error is:
```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
Removing the datadog plugin from the plugin list in `serverless.yml` fixes the problem entirely.
I'm curious to hear if others had problems with this as well, or if maybe there's something wrong with my configuration.

My warmup setup is pretty barebones, with `enabled: true, prewarm: true` and `schedule` set to every 5 minutes.
```json
"serverless": "^2.11.0",
"serverless-plugin-warmup": "^4.9.0",
"serverless-plugin-datadog": "^2.6.0"
```

**Comment by juanjoDiaz** [comment] 2020-12-03 23:40
Hi @judehunter ,

In which order are you setting up the plugins?
`serverless-plugin-warmup` adds an extra function to your service, the warmer. This is a standard function configured to be triggered by a scheduled CloudWatch event.
`serverless-plugin-datadog` seems to be adding a layer to each handler and wrapping each handler in their own.

So `serverless-plugin-warmup` should be declared before `serverless-plugin-datadog`.
The fact that the warmer function is erroring, seems to point that you are already using the right order.

I took a quick look at the `serverless-plugin-datadog` codebase and everything else seems fine.

So other than that, I'd need to get an example project to be able to debug and see what's going on.
And considering that the lambdas don't seem OSS, I'm not sure of how to do that.
You might want to try asking for support on the `serverless-plugin-datadog` end.

**Comment by nholbrook** [comment] 2020-12-08 02:16
@judehunter The `serverless-datadog-plugin` by default overrides the handlers of all functions if you have the `addLayers` flag enabled with their plugin. A solution to this has been merged into the `serverless-plugin-datadog` repo, which allows you to manually exclude functions from this default behavior, and should be included in it's next release. @juanjoDiaz You can feel free to close this issue because it isn't relevant to this plugin (https://github.com/DataDog/serverless-plugin-datadog/pull/87).

**Closed** 2020-12-08 11:05 UTC

**Comment by d-corler** [comment] 2021-04-08 08:45
ℹ To help those who need an immediate response

If you use the default configuration, add this in your [Datadog](https://github.com/DataDog/serverless-plugin-datadog) configuration :
```yaml
custom:
  datadog:
    exclude: 
      - warmUpPluginDefault
```

**Comment by juanjoDiaz** [comment] 2023-05-31 20:48
Hi @astuyve,

Thanks for the good work.

This is a tricky one...
There is a reason why the warmers are set twice.
If you browser through this repo you can find quite a few issues related to other plugins (webpack, rollup, etc..).
The problem is always the same: not all of us use the same lifecycle events.
I asked long time ago the serverless guidance to document the lifecycle events and provide better guidance for us the plugin authors.


The real issue comes from here:
https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/c9ee9fa9a8fa97395d32db0a6aebeeefd34ea3a0/src/index.js#L75

The warmup lambdas are added on the `after:package:initialize` event. Which is the same event used by the `datadog` plugin.
However, the webpack, bundle and similar plugins use the `before:package:createDeploymentArtifacts` event and break things.
For that, I need to reset the warmers during the `before:package:createDeploymentArtifacts` event.
I wish I could get rid of that hack but then I'd break the library for all people bundling their JS.

Ideally, we all should use the same event...
Sadly, that seems unlikely.

I am happy to hear suggestions.
And I am happy to accept any PR as long as it still works with the webpack, bundle and similar plugins :sli

**Comment by juanjoDiaz** [comment] 2023-05-31 22:09
#338 is exactly about that.
Let's discuss there.

Another option is that you implement double events in the datadog plugin like I do here to avoid issues.

**Comment by astuyve** [comment] 2023-05-31 22:29
Yup, sounds good - we're happy to implement whatever is easiest and have similar challenges with bundlers.
