### ISSUE TITLE
Serverless warmup multiple function attachment 

### ISSUE THREAD

**Issue by bwaghmare** [juanjoDiaz/serverless-plugin-warmup#242] opened 2021-01-14 09:14 UTC
How to attach multiple warmer functions for the same lambda.

I.e. Lambda Name - Test-Lambda

```yaml
Test-Lambda:
    warmup:
      enabled: true

warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: 'cron(0/5 10-11 ? * * *)'
      concurrency: 5
    outOfOfficeHoursWarmer:
      enabled: true
      events:
        schedule: 'cron(0/5 4-6 ? * * *)' 
      concurrency: 3
```
      
      
      
  I wanted to ping Test-Lambda as per officeHoursWarmer  and outOfOfficeHoursWarmer

**Comment by juanjoDiaz** [comment] 2021-01-14 11:23
This is a duplicate of #213.

The feature has been released in version 5.
It's documented in the readme and it works exactly as your example config

**Closed** 2021-01-14 11:24 UTC
