### ISSUE TITLE
Temporary folder "warmer" not removed on deploy 

### ISSUE THREAD

**Issue by gshawnr** [juanjoDiaz/serverless-plugin-warmup#298] opened 2022-01-24 20:53 UTC
I encountered an error in version 6.2.0 that does not occur in 6.0.0.  When deploying, the temporary folder warmer (might be warmup) that is created for the deploy is not successfully removed (there is a comment in the deploy log "unable to remove temporary folder warmer/warmup .).  

Unfortunately, I did not save my fail logs.  Let me know if you need more information.

Config:
```yaml
plugins:
  - serverless-bundle
  - serverless-plugin-warmup

custom:
  warmup:
    warmer:
      enabled: true
      events:
        - schedule: cron(0/5 * * * ? *) #Cron Expression for every 5 minutes
      concurrency: 1

functionName:
    handler: handlers/functionName.function
    warmup:
      warmer:
        enabled: false
```

**Comment by juanjoDiaz** [comment] 2022-01-31 19:02
Hi @gshawnr ,

You are right. 6.2.0 accidentally removed support for node 12.

Since node 12, only have a couple of months until EoL, can you simply update to Node 14.X?

**Comment by gshawnr** [comment] 2022-02-01 00:34
Hi @juanjoDiaz 

We actually are running 14x in that service... here is a snippet of the yml:
![image](https://user-images.githubusercontent.com/38596180/151895524-017988d6-1fc1-490b-ae35-2e89944de4f9.png)

**Comment by juanjoDiaz** [comment] 2022-02-01 17:11
that's the runtime.

Node 12 is what I suspect that you run on your machine or in the CI where you are running the `deploy` command.

**Comment by juanjoDiaz** [comment] 2022-02-07 20:40
Closing since the issue is explained and the solution as well.
Feel free to reopen if you think that we left anything behind.

**Closed by juanjoDiaz** 2022-02-07 20:40 UTC

**Comment by gshawnr** [comment] 2022-02-08 00:23
Hi,

Yes you were right I was running 12 locally.  I have not had a change to test again since I've updated my local version.  If I have any issues though when I do, I will follow up.  Thanks.
